[package]
name = "wknd-rt"
version = "0.1.0"
authors = ["Juuso Mikkonen <hello@juusomikkonen.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
